import { CATEGORY } from './emojiConstant'

export default [
  CATEGORY.PEOPLE,
  CATEGORY.NATURE,
  CATEGORY.FOODS,
  CATEGORY.ACTIVITY,
  CATEGORY.PLACES,
  CATEGORY.OBJECTS,
  CATEGORY.SYMBOLS,
  CATEGORY.FLAGS
]
